<a href="https://colab.research.google.com/github/raymart42/ICT110_CS2A_Patriarca/blob/master/Workbook_5/Lesson_2_(NumPy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy for Numerical Computing

In [4]:
import numpy as np #あ import numpy and assign an alias named np

Let's check the version and what's inside the `NumPy` module:

In [5]:
np.__version__ #checking the version by using the alias since we assigned it already

'1.25.2'

In [6]:
print(dir(np)) #checking the content of numpy module

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals'

<a id='commands'></a>
# I. PYTHON MODULES



### Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [48]:
# A.

#create a nested Python list with values from 1-100
nested_list = [[i for i in range(1, 101)]]

#convert the nested Python list into a NumPy ndarray object
A = np.array(nested_list)

#print the shape of the array
print("Shape:", A.shape)

#print the size of the array
print("Size:", A.size)

#print the number of dimensions of the array
print("Number of dimensions:", A.ndim)

#print the maximum value in the array
print("Max value:", np.max(A))

print(nested_list)

Shape: (1, 100)
Size: 100
Number of dimensions: 2
Max value: 100
[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]]


In [49]:
# B.

b = np.ones((5, 5), dtype=int) #create 5x5 integer array filled with ones

print("Shape:", b.shape) #print the shape of the array


print("Size:", b.size) #print the size of the array


print("Number of dimensions:", b.ndim) #print the number of dimensions of the array


Shape: (5, 5)
Size: 25
Number of dimensions: 2


In [51]:
#create an array of values from -5 to +5
c = np.arange(-5, 6)

#print the array
print(c)

#multiply each value by 2
c *= 2

#print the resulting array
print(c)


[-5 -4 -3 -2 -1  0  1  2  3  4  5]
[-10  -8  -6  -4  -2   0   2   4   6   8  10]


### Exercise

A. Choose the values from the range of numbers 1 to 100.
1. Create an array with 30 values within the range of numbers given. You can choose your own start value and stop value. However, the incrementing value will be 2.
   * Explain what is the result briefly by writing a comment before the code.
2. Multiply the resulting array with 3. Print the result.

In [52]:
# 1.
#create a range from 1 to 61(excluded) with incrementing value of 2
a = np.arange(1, 61, 2)
print(a)
a.size

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59]


30

In [54]:
# 2.

arrayMultiply = a * 3
print(arrayMultiply)

[  3   9  15  21  27  33  39  45  51  57  63  69  75  81  87  93  99 105
 111 117 123 129 135 141 147 153 159 165 171 177]


### Exercise

A. Create a four-dimensional array of random integers in the interval [0, 12]. Print the result.
1. Get the dimensions, shape, and size.
    * Explain what is the result briefly by writing a comment before the code.

B. Get the maximum number for each dimensions and display it.
   * Explain what is the result briefly by writing a comment before the code.

C. Multipy each array with 4. What is its result?
    * Write a brief explanation on the multiplication process.


In [57]:
# A.
#create four-dimensional array of random integers in the interval [0, 12]
fourD = np.random.randint(0, 13, size=(3, 4, 2, 5))

#print the result
print("Four-dimensional array:")
print(fourD)

#print the dimensions of the array which is 4
print("Dimensions:", fourD.ndim)

#print the shape of the array which is (3, 4, 2, 5)
print("Shape:", fourD.shape)

#print the size of the array which is 120
print("Size:", fourD.size)


Four-dimensional array:
[[[[ 8 12  6 11  7]
   [ 6  2  5  1  4]]

  [[ 6  1  8  6  5]
   [ 5  5 11  7  2]]

  [[ 7  1  8  9 11]
   [10  8  7  0  7]]

  [[11 11  6  0  6]
   [ 7  1  6  9  1]]]


 [[[ 4 10  7  5  0]
   [ 6 11  8  8  7]]

  [[11  0  0  2 11]
   [ 5 12  3  6  3]]

  [[ 5  7  6 12 12]
   [10 12  3  2  9]]

  [[12  9  7  6  7]
   [ 8  4  3  6  9]]]


 [[[ 5  1  6  8  6]
   [10  2  4  9  3]]

  [[ 6  6  9  6  6]
   [ 1  0  5  2  0]]

  [[ 0  0  7  8  4]
   [ 8  0  3 12  5]]

  [[ 2  0 11  0 10]
   [ 9  8  6 10  9]]]]
Dimensions: 4
Shape: (3, 4, 2, 5)
Size: 120


In [63]:
# B.

#get the maximum number for each dimension and display it
print(fourD.max(axis=(0, 1, 2)))


[12 12 11 12 12]


In [65]:
# C.
#multiply each array with 4
arrayMultiply = fourD * 4

#print the resulting array after multiplication
print("Result after multiplying each array element by 4:")
print(arrayMultiply)

#We multiply each element of the four-dimensional array fourD by 4 using the * operator.
#This operation results in a new array arrayMultiply where each element of the original array is multiplied by 4.

Result after multiplying each array element by 4:
[[[[32 48 24 44 28]
   [24  8 20  4 16]]

  [[24  4 32 24 20]
   [20 20 44 28  8]]

  [[28  4 32 36 44]
   [40 32 28  0 28]]

  [[44 44 24  0 24]
   [28  4 24 36  4]]]


 [[[16 40 28 20  0]
   [24 44 32 32 28]]

  [[44  0  0  8 44]
   [20 48 12 24 12]]

  [[20 28 24 48 48]
   [40 48 12  8 36]]

  [[48 36 28 24 28]
   [32 16 12 24 36]]]


 [[[20  4 24 32 24]
   [40  8 16 36 12]]

  [[24 24 36 24 24]
   [ 4  0 20  8  0]]

  [[ 0  0 28 32 16]
   [32  0 12 48 20]]

  [[ 8  0 44  0 40]
   [36 32 24 40 36]]]]
